### ISSUE TITLE
email login not working on https://wallet.tx.xyz on mobile

### ISSUE THREAD

**Issue by jpdreamos** [tkhq/demo-passkey-wallet#19]
When I visit https://wallet.tx.xyz/ using my desktop, if I attempt to sign up with a brand new email, and click "Continue with email", I receive the email. However, when I click the link in the email on my phone, both the desktop browser and mobile browser hang in this state indefinitely:

![telegram-cloud-photo-size-5-6089255893712617384-y](https://github.com/user-attachments/assets/a2198ece-a587-4fde-b61d-362be5ce0475)

![image](https://github.com/user-attachments/assets/8440227b-9788-4423-9762-2f4adb27d9fc)

In contrast, if I open up my email client on my desktop, then click the Sign In link from there, it works fine.

Also, if I initiate login from iOS Chrome, and open the email Sign In button in iOS Chrome, it works. But if I start in Chrome and open the Sign In link from iOS Safari it fails. Is this expected?

Am I obligated to open the Sign In link on the same device/session where I initiated the login?

**Comment by lthibault** [comment]
Hey @jpdreamos, are you able to re-run this and show me any output from the JS console in the browser?

Also, does this failure only happen in iOS Safari, or does it happen any time you open the link an a different browser than the one that created it?

**Comment by coindegen** [comment]
hi @lthibault , I confirmed with Bryce that this is a security feature by design. Closing, thanks!

**Comment by jpdreamos** [comment]
hi @lthibault, I confirmed with Bryce that this is a security feature by design. Closing, thanks!
